name: Deploy

on:
  workflow_dispatch:
    inputs:
      api:
        description: 'Select Service To Deploy'
        required: true
        default: 'account-service'
        type: choice
        options:
          - 'evolus-admin-tools'
          - 'consumer-rewards'
          - 'evolus-portal'
        
      environment:
        description: 'Select environment to deployment'
        required: true
        default: 'dev'
        type: choice
        options:
          - 'staging'
          - 'dev'
          - 'dev-sandbox'
          - 'dev2'

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

env:
  AWS_REGION: ${{secrets.AWS_REGION}}
  AWS_PROFILE: ${{secrets.AWS_PROFILE}}
  NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
  AWS_OIDC_ROLE: ${{ secrets.AWS_OIDC_ROLE }} 
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
  SLACK_CHANNEL_ID: ${{secrets.SLACK_CHANNEL_ID}}
  CI: false

jobs:
  send-slack:
    runs-on: ubuntu-latest
    name: send-slack
    steps:
      - name: Extract branch name
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Started Slack notification
        id: slack_notification
        uses: adamkdean/simple-slack-notify@v1.1.2
        with:
          channel: '${{ env.SLACK_CHANNEL_ID }}'
          status: ${{ job.status }}
          success_text: |
            \`Started\` Deployment of \`Deploy_Full_Frontend_Apps\` to \`${{ inputs.environment }}\` from \`${env.BRANCH}\`
            \`\`\`
            User Name: ${{ github.actor }}
            Commit ID: ${{ github.sha }}
            \`\`\`
          cancelled_text: |
            \`Cancelled\` Deployment of \`Deploy_Full_Frontend_Apps\` to \`${{ inputs.environment }}\` from \`${env.BRANCH}\`
            \`\`\`
            User Name: ${{ github.actor }}
            Commit ID: ${{ github.sha }}
            Action URL: ${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}
            \`\`\`


  deploy_frontend_apps:
    runs-on: ubuntu-latest
    needs: send-slack
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        service: ["consumer-rewards", "evolus-admin-tools", "evolus-portal"]
        experimental: [true]
    name: Deploy "${{ matrix.service }}" to "${{ inputs.environment }}"


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploying "${{ matrix.service }}" to "${{ inputs.environment }}"
        id: apps
        run: |
          cd client/web/${{ inputs.environment }}
           
              
      - name: Set job status
        id: set_status_failure
        if: ${{ failure() }}
        run: echo "::set-output name=status::failure"
    
        # Mark the job as successful if there's no error during deployment
      - name: Set job status
        id: set_status_success
        if: ${{ success() }}
        run: echo "::set-output name=status::success"

    outputs:
        failure: ${{ steps.set_status_failure.outputs.status }}
        success: ${{ steps.set_status_success.outputs.status }}

  send-failed:
    runs-on: ubuntu-latest
    name: send-slack2
    needs: [send-slack, deploy_frontend_apps]
    steps:
      - name: Extract branch name
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set status variables
        id: set_status_variables
        run: |
           echo "::set-output name=status::${{ needs.deploy_frontend_apps.outputs.failure }} ${{ needs.deploy_frontend_apps.outputs.success }}"
   
      - name: Send Slack notification
        id: slack_notification_failed
        uses: adamkdean/simple-slack-notify@v1.1.2
        with:
          channel: '${{ env.SLACK_CHANNEL_ID }}'
          status: ${{ steps.set_status_variables.outputs.status }}
          success_text: |
            \`Succeded\` Deployment of \`Deploy_Full_Frontend_Apps\` to \`${{ inputs.environment }}\` from \`${env.BRANCH}\`
            \`\`\`
            User Name: ${{ github.actor }}
            Commit ID: ${{ github.sha }}
            \`\`\`
          cancelled_text: |
            \`Cancelled\` Deployment of \`Deploy_Full_Frontend_Apps\` to \`${{ inputs.environment }}\` from \`${env.BRANCH}\`
            \`\`\`
            User Name: ${{ github.actor }}
            Commit ID: ${{ github.sha }}
            Action URL: ${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}
            \`\`\`
          failure_text: |
            \`Started\` Deployment of \`Deploy_Full_Frontend_Apps\` to \`${{ inputs.environment }}\` from \`${env.BRANCH}\`
            \`\`\`
            User Name: ${{ github.actor }}
            Commit ID: ${{ github.sha }}
            \`\`\`
