name: test-3

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deployment'
        required: true
        default: 'dev'
        type: choice
        options:
          - 'staging'
          - 'dev'
          - 'dev-sandbox'
          - 'dev2'

          
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

env:
  AWS_REGION: ${{secrets.AWS_REGION}}
  AWS_PROFILE: ${{secrets.AWS_PROFILE}}
  NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
  AWS_OIDC_ROLE: ${{ secrets.AWS_OIDC_ROLE }} 
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
  SLACK_CHANNEL_ID: ${{secrets.SLACK_CHANNEL_ID}}
  CI: false


jobs:
  send-slack:
    runs-on: ubuntu-latest
    name: send-slack
    steps:
      - name: Extract branch name
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Started Slack notification
        id: slack_notification
        uses: adamkdean/simple-slack-notify@v1.1.2
        with:
          channel: '${{ env.SLACK_CHANNEL_ID }}'
          status: ${{ job.status }}
          success_text: |
            ${{ github.actor }} \`Started\` Deployment of \`Deploy_Full_Frontend_Apps\` to \`${{ inputs.environment }}\` from \`${env.BRANCH}\` @ ${{ github.sha }}
 

  deploy_frontend_apps:
    runs-on: ubuntu-latest
    needs: send-slack
    strategy:
      fail-fast: false
      matrix:
        service: ["consumer-rewards", "evolus-admin-tools", "evolus-portal", "test", "test1", "test2", "test3"]
    name: Deploy "${{ matrix.service }}" to "${{ inputs.environment }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploying "${{ matrix.service }}" to "${{ inputs.environment }}"
        id: apps
        run: |
          echo hello form "${{ matrix.service }}"
          sleep 10
          cd client/web/${{ matrix.service }}
          ls -al

  send-failed:
    runs-on: ubuntu-latest
    name: Failed
    needs: deploy_frontend_apps
    if: failure()
    steps:
      - name: Extract branch name
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Send Slack notification
        id: slack_notification_failed
        uses: adamkdean/simple-slack-notify@v1.1.2
        with:
          channel: '${{ env.SLACK_CHANNEL_ID }}'
          status: failure
          failure_text: |
            ${{ github.actor }} \`Failed\` Deployment of \`Deploy_Full_Frontend_Apps\` to \`${{ inputs.environment }}\` from \`${env.BRANCH}\` @ ${{ github.sha }}


  send-success:
    runs-on: ubuntu-latest
    name: success
    needs: deploy_frontend_apps
    if: success()
    steps:
      - name: Extract branch name
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Send Slack notification
        id: slack_notification_failed
        uses: adamkdean/simple-slack-notify@v1.1.2
        with:
          channel: '${{ env.SLACK_CHANNEL_ID }}'
          status: success
          success_text: |
            ${{ github.actor }} \`Succeded\` Deployment of \`Deploy_Full_Frontend_Apps\` to \`${{ inputs.environment }}\` from \`${env.BRANCH}\` @ ${{ github.sha }}

  send-cancelled:
    runs-on: ubuntu-latest
    name: cancelled
    needs: deploy_frontend_apps
    if: cancelled()
    steps:
      - name: Extract branch name
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Send Slack notification
        id: slack_notification_failed
        uses: adamkdean/simple-slack-notify@v1.1.2
        with:
          channel: '${{ env.SLACK_CHANNEL_ID }}'
          status: cancelled
          cancelled_text: |
            ${{ github.actor }} \`Cancelled\` Deployment of \`Deploy_Full_Frontend_Apps\` to \`${{ inputs.environment }}\` from \`${env.BRANCH}\` @ ${{ github.sha }}
